### ISSUE TITLE
Add 3 phases

### ISSUE THREAD

**Issue by jorka57** [Aohzan/ecodevices#19]
Hello,

Could You add this entities :

- intensity per phase
- HP / HC

Thanks You

**Comment by Aohzan** [comment]
Hello, you have them in main entity attributes, you can create separated entities with template sensor, exemple:
```yaml
---
- platform: template
  sensors:
    intensity_phase_1:
      unique_id: intensity_phase_1
      friendly_name: "Intensité phase 1"
      unit_of_measurement: "Wh"
      value_template: "{{ state_attr('sensor.compteur_linky', 'intensite_now_ph1') | int }}"
```
