### ISSUE TITLE
Gas consumption

### ISSUE THREAD

**Issue by Berco63** [Aohzan/ecodevices#55]
Gas consumption.

I have noticed several times that when HA is stopped, the gas meters are wrong.

Let me explain, when HA is restarted, the gas consumption graph for the current time slot contains the total consumption since the beginning of the day.

Here is the sensor configuration:

#
# Daily gas consumption
#
```
- name: infos_chaudiere_consommation_jour_eau_chaude
state_topic: "/chaudiere_viessmann/etat"
value_template: >
{% if value_json.infos_chaudiere_consommation_jour_eau_chaude is defined %}
{{value_json.infos_chaudiere_consommation_jour_eau_chaude}}
{% else %}
{{states('sensor.infos_chaudiere_consommation_jour_eau_chaude') | int(0) }}
{% endif %}
state_class: total_increasing
device_class: energy
unit_of_measurement: kWh

- name: infos_chaudiere_consommation_jour_chauffage
state_topic: "/chaudiere_viessmann/etat"
value_template: >
{% if value_json.infos_chaudiere_consommation_jour_chauffage is defined %}
{{value_json.infos_chaudiere_consommation_jour_chauffage}}
{% else %}
{{states('sensor.infos_chaudiere_consommation_jour_chauffage') | int(0) }}
{% endif %}
device_class: energy
state_class: total_increasing
unit_of_measurement: kWh
```

Recorder from configuration.yaml
```
#----------------------------------------------
#recorder:
#----------------------------------------------
#
recorder:
purge_keep_days: 10
include:
entity_globs:
- sensor.teleinfo_*
- sensor.universal_binary_sensor_air_temperature_*
- sensor.motion_sensor_air_temperature
entities:
- sensor.infos_boiler_ambient_temp
- sensor.infos_boiler_ecs_temp
- sensor.infos_boiler_probe_temp
- sensor.infos_boiler_heating_day_consumption
- sensor.infos_boiler_hot_water_consumption
- sensor.processor_temperature
 exclude:
 event_types:
 - call_service # Don't record actions
```
As you can see in the provided image, the 14h - 15h range contains the cumulative since 0h.

![ecodevice](https://github.com/user-attachments/assets/ddcd19d3-d705-4f10-a384-50567a43e86e)

Maybe it's just a configuration issue?
I haven't seen this type of error before.
